// ============================================================
// Sigma Rule Parser — Extract ATT&CK tags from YAML rules
// ============================================================

/**
 * Parse Sigma YAML content and extract ATT&CK technique IDs.
 * Sigma ATT&CK tag format: attack.tXXXX or attack.tXXXX.YYY
 */
export function parseSigmaRule(yamlContent) {
  try {
    // Simple regex-based parser (no heavy yaml lib needed for tag extraction)
    const rule = {};

    // Extract title
    const titleMatch = yamlContent.match(/^title:\s*(.+)$/m);
    rule.title = titleMatch ? titleMatch[1].trim() : 'Unknown Rule';

    // Extract description
    const descMatch = yamlContent.match(/^description:\s*(.+)$/m);
    rule.description = descMatch ? descMatch[1].trim() : '';

    // Extract level
    const levelMatch = yamlContent.match(/^level:\s*(.+)$/m);
    rule.level = levelMatch ? levelMatch[1].trim() : 'medium';

    // Extract status
    const statusMatch = yamlContent.match(/^status:\s*(.+)$/m);
    rule.status = statusMatch ? statusMatch[1].trim() : 'experimental';

    // Extract id
    const idMatch = yamlContent.match(/^id:\s*(.+)$/m);
    rule.id = idMatch ? idMatch[1].trim() : generateId();

    // Extract tags — look for attack.tXXXX pattern
    const tagsSection = yamlContent.match(/^tags:\s*\n((?:\s+-.+\n?)+)/m);
    const techniques = [];
    const tactics = [];

    if (tagsSection) {
      const tagLines = tagsSection[1].split('\n');
      tagLines.forEach(line => {
        const tagMatch = line.match(/^\s+-\s+attack\.(t\d{4}(?:\.\d{3})?)/i);
        if (tagMatch) {
          techniques.push(tagMatch[1].toUpperCase());
        }
        const tacticMatch = line.match(/^\s+-\s+attack\.(\w[\w_]+)$/i);
        if (tacticMatch && !tacticMatch[1].match(/^t\d{4}/i)) {
          tactics.push(tacticMatch[1]);
        }
      });
    }

    rule.techniques = [...new Set(techniques)];
    rule.tactics = [...new Set(tactics)];
    rule.source = 'sigma';

    return { success: true, rule };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

/**
 * Parse multiple Sigma rules from a single file (YAML multi-document)
 */
export function parseMultipleSigmaRules(content) {
  // Split on YAML document separators
  const documents = content.split(/^---$/m).filter(doc => doc.trim());
  const results = [];

  documents.forEach(doc => {
    if (doc.trim()) {
      const result = parseSigmaRule(doc);
      if (result.success && result.rule.techniques.length > 0) {
        results.push(result.rule);
      }
    }
  });

  // If no separator found, try as single document
  if (results.length === 0 && content.trim()) {
    const result = parseSigmaRule(content);
    if (result.success) results.push(result.rule);
  }

  return results;
}

/**
 * Parse an ATT&CK Navigator layer JSON (import existing layers)
 */
export function parseNavigatorLayer(jsonContent) {
  try {
    const layer = JSON.parse(jsonContent);
    const rules = [];

    if (layer.techniques) {
      layer.techniques.forEach(t => {
        if (t.enabled !== false) {
          rules.push({
            id: generateId(),
            title: `Navigator: ${t.techniqueID}`,
            techniques: [t.techniqueID],
            tactics: [],
            level: 'medium',
            status: 'imported',
            source: 'navigator',
            comment: t.comment || '',
          });
        }
      });
    }

    return { success: true, rules, layerName: layer.name || 'Imported Layer' };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

/**
 * Generate a Navigator-compatible layer from coverage results
 */
export function generateNavigatorLayer(techniqueScores, layerName = 'Purple Team Gap Analysis') {
  const techniques = Object.values(techniqueScores).map(ts => ({
    techniqueID: ts.id,
    score: ts.score,
    color: getLayerColor(ts.score),
    comment: `Coverage Score: ${ts.score}/100 | Level: ${ts.level}`,
    enabled: true,
    metadata: [],
    links: [],
  }));

  return {
    name: layerName,
    versions: { attack: '15', navigator: '4.9', layer: '4.5' },
    domain: 'enterprise-attack',
    description: `Generated by Purple Team Mapper — ${new Date().toISOString()}`,
    filters: { platforms: ['Linux', 'macOS', 'Windows', 'Azure AD', 'Office 365', 'SaaS', 'IaaS'] },
    sorting: 0,
    layout: { layout: 'side', aggregateFunction: 'max', showID: true, showName: true, showAggregateScores: true, countUnscored: false, expandedSubtechniques: 'annotated' },
    hideDisabled: false,
    techniques,
    gradient: {
      colors: ['#ef4444', '#f97316', '#eab308', '#22c55e'],
      minValue: 0,
      maxValue: 100,
    },
    legendItems: [
      { label: 'No Coverage (0)', color: '#ef4444' },
      { label: 'Low Coverage (1–33)', color: '#f97316' },
      { label: 'Medium Coverage (34–66)', color: '#eab308' },
      { label: 'High Coverage (67–100)', color: '#22c55e' },
    ],
    metadata: [],
    links: [],
    showTacticRowBackground: true,
    tacticRowBackground: '#1e1e3a',
    selectTechniquesAcrossTactics: true,
    selectSubtechniquesWithParent: false,
    selectVisibleTechniques: false,
  };
}

function getLayerColor(score) {
  if (score === 0) return '#ef4444';
  if (score <= 33) return '#f97316';
  if (score <= 66) return '#eab308';
  return '#22c55e';
}

function generateId() {
  return 'rule-' + Math.random().toString(36).substr(2, 9);
}

/**
 * Export data as CSV
 */
export function exportAsCSV(techniqueScores, tacticMap) {
  const headers = ['Technique ID', 'Technique Name', 'Tactic', 'Score', 'Coverage Level', 'Covering Controls', 'Detection Rules'];
  const rows = Object.values(techniqueScores).map(ts => [
    ts.id,
    `"${ts.name}"`,
    tacticMap[ts.tactic]?.name || ts.tactic,
    ts.score,
    ts.level,
    ts.coveringControls?.map(c => c.name).join('; ') || '',
    ts.coveringRules?.map(r => r.title).join('; ') || '',
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}
